### ISSUE TITLE
How could i retrieve didselect item on tableview?

### ISSUE THREAD

**Issue by themythIOS** [yannickl/FlowingMenu#8] opened 2016-04-22 07:56 UTC
On the menu viewcontroller.. i tried to add my custom delegate, no luck retrieving and return data to another viewcontroller.

**Comment by themythIOS** [comment] 2016-04-22 08:34
i tried to disable the dismiss to monitor the menu view controll. It has a very much delay on did select of a tableview cell. Or i miss something?

**Comment by yannickl** [comment] 2016-04-25 15:23
I'm sorry I don't understand your problem. What is your problem exactly, what do you need? Have you also some sample code?

**Comment by elcura** [comment] 2016-04-29 08:32
Hi, yannickl

I have the same problem, the issue is when you show the MENU View controller with a TableView inside, when you try to know what Row did you selected, the recognizer gesture of flowingmenu takes the control, and this method:

 func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath)
    {
        print ("row MenuViewcontroller: (indexPath.row)")

 }

Never triggers the row i selected before the Menu View controller close.

The example itself you provide, you can test it, When Menu appears it shows a TableView with names, but you cannot access what name did you Tap.

Sorry for my english.

Rafa.

**Comment by elcura** [comment] 2016-04-29 09:01
Hi Again,
I Solved the problem.
In the FlowingMenuTransitionManager+UIGestureRecognizer.swift
I add this line: tapGesture.cancelsTouchesInView = false

On func: addTapGesture(view: UIView) 
Example:
  func addTapGesture(view: UIView) {
    let tapGesture                  = UITapGestureRecognizer()
  tapGesture.cancelsTouchesInView = false
    tapGesture.numberOfTapsRequired = 1
    tapGesture.addTarget(self, action: #selector(FlowingMenuTransitionManager.tapToDismissAction(_:)))
       view.addGestureRecognizer(tapGesture)
  }

Now, i can tap the Row, know what element i selected and dismiss the Menu

Rafa.

**Comment by khushbooPS** [comment] 2016-05-07 12:36
Hi Yannick,
I have same issue, I did not call didSelectRowAtIndexPath delegate. 
I used:

> tapGesture.cancelsTouchesInView= false

 But I did not get success. What i do? 
Please help me sir.

Khushi.

**Comment by yannickl** [comment] 2016-10-10 08:15
It should be fixed now!

**Closed as completed by yannickl** 2016-10-10 08:15 UTC
